import assert from "node:assert/strict";
import { evaluateCommand } from "./policy.ts";
import { test } from "./test-harness.ts";

type ProviderCorpus = {
	executable: "aws" | "az" | "gcloud";
	reads: string[];
	approvals: string[];
};

const AWS_CORPUS: ProviderCorpus = {
	executable: "aws",
	reads: [
		"aws ec2 describe-instances",
		"aws ec2 describe-images --owners self",
		"aws ec2 describe-security-groups",
		"aws ec2 describe-vpcs",
		"aws ec2 describe-subnets",
		"aws ec2 describe-route-tables",
		"aws ec2 describe-volumes",
		"aws s3 ls s3://example-bucket",
		"aws s3api list-buckets",
		"aws s3api list-objects-v2 --bucket example-bucket",
		"aws s3api head-object --bucket example-bucket --key report.json",
		"aws s3api get-bucket-location --bucket example-bucket",
		"aws s3api get-object --bucket example-bucket --key public.json ./public.json",
		"aws s3api select-object-content --bucket example-bucket --key data.csv --expression 'select * from s3object'",
		"aws iam list-users",
		"aws iam get-user --user-name reader",
		"aws iam list-roles",
		"aws iam get-role --role-name ReadOnlyRole",
		"aws iam list-policies --scope Local",
		"aws iam simulate-principal-policy --policy-source-arn arn:aws:iam::123456789012:role/reader --action-names s3:GetObject",
		"aws rds describe-db-instances",
		"aws rds describe-db-clusters",
		"aws rds describe-db-snapshots",
		"aws rds download-db-log-file-portion --db-instance-identifier db --log-file-name error/postgresql.log",
		"aws ecs list-clusters",
		"aws ecs describe-clusters --clusters production",
		"aws ecs list-services --cluster production",
		"aws ecs describe-services --cluster production --services api",
		"aws eks list-clusters",
		"aws eks describe-cluster --name production",
		"aws eks list-nodegroups --cluster-name production",
		"aws logs describe-log-groups",
		"aws logs describe-log-streams --log-group-name /app/api",
		"aws logs filter-log-events --log-group-name /app/api",
		"aws logs get-log-events --log-group-name /app/api --log-stream-name web",
		"aws logs tail /app/api --since 1h",
		"aws cloudwatch list-metrics",
		"aws cloudwatch get-metric-data --metric-data-queries file://queries.json --start-time 2025-01-01T00:00:00Z --end-time 2025-01-01T01:00:00Z",
		"aws cloudwatch describe-alarms",
		"aws cloudformation list-stacks",
		"aws cloudformation describe-stacks --stack-name production",
		"aws cloudformation list-stack-resources --stack-name production",
		"aws cloudformation get-template --stack-name production",
		"aws cloudformation estimate-template-cost --template-body file://template.json",
		"aws route53 list-hosted-zones",
		"aws route53 get-hosted-zone --id Z123",
		"aws route53 list-resource-record-sets --hosted-zone-id Z123",
		"aws route53 test-dns-answer --hosted-zone-id Z123 --record-name example.com --record-type A",
		"aws route53domains check-domain-availability --domain-name example.com",
		"aws dynamodb list-tables",
		"aws dynamodb describe-table --table-name jobs",
		"aws dynamodb scan --table-name jobs",
		"aws dynamodb query --table-name jobs --key-condition-expression 'pk = :pk'",
		"aws organizations list-accounts",
		"aws organizations describe-organization",
		"aws cognito-idp admin-get-user --user-pool-id pool-id --username reader",
		"aws acm list-certificates",
		"aws acm describe-certificate --certificate-arn arn:aws:acm:us-east-1:123:certificate/abc",
		"aws ecr describe-repositories",
		"aws ecr list-images --repository-name api",
		"aws ecr describe-images --repository-name api",
		"aws autoscaling describe-auto-scaling-groups",
		"aws elbv2 describe-load-balancers",
		"aws athena get-query-results --query-execution-id query-id",
		"aws sts get-caller-identity",
		"aws configure list-profiles",
	],
	approvals: [
		"aws ec2 run-instances --image-id ami-123 --instance-type t3.micro",
		"aws ec2 start-instances --instance-ids i-123",
		"aws ec2 stop-instances --instance-ids i-123",
		"aws ec2 reboot-instances --instance-ids i-123",
		"aws ec2 terminate-instances --instance-ids i-123",
		"aws ec2 create-security-group --group-name api --description api",
		"aws ec2 authorize-security-group-ingress --group-id sg-123 --protocol tcp --port 443 --cidr 10.0.0.0/8",
		"aws ec2 modify-instance-attribute --instance-id i-123 --instance-type Value=t3.large",
		"aws s3 cp ./artifact.zip s3://example-bucket/artifact.zip",
		"aws s3 sync ./dist s3://example-bucket",
		"aws s3 rm s3://example-bucket/old.zip",
		"aws s3api put-object --bucket example-bucket --key list --body ./artifact.zip",
		"aws s3api delete-object --bucket example-bucket --key old.zip",
		"aws iam create-role --role-name deployer --assume-role-policy-document file://trust.json",
		"aws iam attach-role-policy --role-name deployer --policy-arn arn:aws:iam::aws:policy/AdministratorAccess",
		"aws iam put-role-policy --role-name deployer --policy-name inline --policy-document file://policy.json",
		"aws iam delete-user --user-name reader",
		"aws iam create-access-key --user-name reader",
		"aws rds create-db-instance --db-instance-identifier db --engine postgres --db-instance-class db.t3.micro",
		"aws rds modify-db-instance --db-instance-identifier db --allocated-storage 100",
		"aws rds delete-db-instance --db-instance-identifier db --skip-final-snapshot",
		"aws ecs create-cluster --cluster-name production",
		"aws ecs update-service --cluster production --service api --desired-count 3",
		"aws ecs delete-service --cluster production --service api --force",
		"aws eks create-cluster --name production --role-arn arn:aws:iam::123:role/eks --resources-vpc-config subnetIds=subnet-1",
		"aws eks update-cluster-version --name production --version 1.32",
		"aws logs put-retention-policy --log-group-name /app/api --retention-in-days 30",
		"aws cloudwatch put-metric-alarm --alarm-name errors --comparison-operator GreaterThanThreshold --evaluation-periods 1 --metric-name Errors --namespace App --period 60 --statistic Sum --threshold 1",
		"aws cloudformation deploy --template-file template.yaml --stack-name production",
		"aws cloudformation delete-stack --stack-name production",
		"aws dynamodb update-table --table-name jobs --billing-mode PAY_PER_REQUEST",
		"aws dynamodb delete-table --table-name jobs",
		"aws organizations move-account --account-id 123 --source-parent-id r-root --destination-parent-id ou-target",
		"aws acm request-certificate --domain-name example.com",
		"aws ecr delete-repository --repository-name api --force",
		"aws autoscaling set-desired-capacity --auto-scaling-group-name api --desired-capacity 5",
		"aws elbv2 modify-load-balancer-attributes --load-balancer-arn arn:aws:elasticloadbalancing:region:123:loadbalancer/app/api --attributes Key=deletion_protection.enabled,Value=true",
		"aws secretsmanager list-secrets",
		"aws secretsmanager get-secret-value --secret-id database",
		"aws ssm get-parameter --name /production/password --with-decryption",
		"aws ssm get-parameter-history --name /production/password --with-decryption",
		"aws ecr get-login-password",
		"aws eks get-token --cluster-name production",
		"aws apigateway get-api-key --api-key abc --include-value",
		"aws lambda list-functions",
		"aws lambda get-function-configuration --function-name api",
		"aws ecs describe-task-definition --task-definition api",
		"aws batch describe-job-definitions",
		"aws sts get-session-token",
		"aws sts assume-role --role-arn arn:aws:iam::123:role/admin --role-session-name test",
		"aws redshift get-cluster-credentials-with-iam --db-name production",
		"aws lightsail get-instance-access-details --instance-name web",
		"aws configure set region us-east-1",
		"aws configure export-credentials",
		"aws configure import --csv file://credentials.csv",
		"aws sso login --profile production",
		"aws madeup inspect-resource",
	],
};

const AZ_CORPUS: ProviderCorpus = {
	executable: "az",
	reads: [
		"az vm list",
		"az vm show --resource-group production --name web",
		"az vm get-instance-view --resource-group production --name web",
		"az vm list-ip-addresses --resource-group production",
		"az vm assess-patches --resource-group production --name web",
		"az vm image list --offer UbuntuServer --all",
		"az vm image list-publishers --location eastus",
		"az vm image list-offers --location eastus --publisher Canonical",
		"az vm extension list --resource-group production --vm-name web",
		"az vmss list",
		"az vmss show --resource-group production --name api",
		"az group list",
		"az group show --name production",
		"az group exists --name production",
		"az resource list --resource-group production",
		"az resource show --ids /subscriptions/123/resourceGroups/production/providers/Microsoft.Compute/virtualMachines/web",
		"az account list",
		"az account show",
		"az account list-locations",
		"az network vnet list",
		"az network vnet show --resource-group production --name main",
		"az network vnet subnet list --resource-group production --vnet-name main",
		"az network nsg list",
		"az network public-ip list",
		"az network lb list",
		"az network application-gateway list",
		"az network watcher show-topology --resource-group production --location eastus",
		"az network watcher test-connectivity --source-resource web --dest-address example.com --dest-port 443",
		"az internet-analyzer test list --resource-group production --profile-name profile",
		"az load test list --load-test-resource load-tests --resource-group production",
		"az storage account list",
		"az storage account show --resource-group production --name data",
		"az storage account check-name --name data",
		"az storage container list --account-name data",
		"az storage container show --account-name data --name public",
		"az storage blob list --account-name data --container-name public",
		"az storage blob show --account-name data --container-name public --name report.json",
		"az storage blob exists --account-name data --container-name public --name report.json",
		"az storage blob url --account-name data --container-name public --name report.json",
		"az acr list",
		"az acr show --name images",
		"az acr check-name --name images",
		"az acr repository list --name images",
		"az aks list",
		"az aks show --resource-group production --name cluster",
		"az aks nodepool list --resource-group production --cluster-name cluster",
		"az aks nodepool show --resource-group production --cluster-name cluster --name system",
		"az aks check-acr --resource-group production --name cluster --acr images.azurecr.io",
		"az containerapp list --resource-group production",
		"az containerapp show --resource-group production --name api",
		"az containerapp revision list --resource-group production --name api",
		"az containerapp logs show --resource-group production --name api --tail 30",
		"az webapp list --resource-group production",
		"az webapp show --resource-group production --name api",
		"az webapp log tail --resource-group production --name api",
		"az functionapp list --resource-group production",
		"az functionapp show --resource-group production --name worker",
		"az keyvault list",
		"az keyvault show --name production",
		"az keyvault key list --vault-name production",
		"az keyvault certificate list --vault-name production",
		"az role assignment list --assignee reader@example.com",
		"az role definition list",
		"az monitor metrics list --resource resource-id",
		"az monitor activity-log list --resource-group production",
		"az monitor log-analytics query --workspace workspace-id --analytics-query 'AzureActivity | take 10'",
		"az monitor log-analytics query-pack query list --resource-group production --query-pack-name shared",
		"az graph query -q 'Resources | limit 10'",
		"az sql server list",
		"az sql db list --resource-group production --server database",
		"az deployment group list --resource-group production",
		"az deployment group show --resource-group production --name current",
		"az deployment group what-if --resource-group production --template-file main.bicep",
		"az deployment group validate --resource-group production --template-file main.bicep",
		"az lock list --resource-group production",
		"az restore-point collection list --resource-group production --vm-name web",
		"az search service list --resource-group production",
		"az ad signed-in-user show",
		"az version",
	],
	approvals: [
		"az vm create --resource-group production --name web --image Ubuntu2204",
		"az vm start --resource-group production --name web",
		"az vm stop --resource-group production --name web",
		"az vm restart --resource-group production --name web",
		"az vm deallocate --resource-group production --name web",
		"az vm resize --resource-group production --name web --size Standard_D4s_v5",
		"az vm delete --resource-group production --name web --yes",
		"az vm open-port --resource-group production --name web --port 22",
		"az vm run-command invoke --resource-group production --name list --command-id RunShellScript --scripts 'uptime'",
		"az group create --name production --location eastus",
		"az group delete --name production --yes",
		"az network vnet create --resource-group production --name main --address-prefixes 10.0.0.0/16",
		"az network vnet subnet update --resource-group production --vnet-name main --name app --address-prefixes 10.0.1.0/24",
		"az network nsg rule create --resource-group production --nsg-name web --name allow-ssh --priority 100 --access Allow",
		"az network public-ip delete --resource-group production --name web",
		"az network watcher flow-log configure --resource-group production --nsg web --enabled true",
		"az internet-analyzer test delete --resource-group production --profile-name profile --name list",
		"az load test create --load-test-resource load-tests --resource-group production --test-id list --test-plan test.jmx",
		"az storage account create --resource-group production --name data --sku Standard_LRS",
		"az storage account update --resource-group production --name data --https-only true",
		"az storage account delete --resource-group production --name data --yes",
		"az storage blob upload --account-name data --container-name public --name list --file ./report.json",
		"az storage blob upload-batch --account-name data --destination public --source ./dist",
		"az storage blob delete --account-name data --container-name public --name old.json",
		"az storage blob lease acquire list --account-name data --container-name public",
		"az storage blob download --account-name data --container-name private --name secret.txt --file ./secret.txt",
		"az acr create --resource-group production --name images --sku Standard",
		"az acr build --registry images --image api:latest .",
		"az acr login --name images --expose-token",
		"az aks create --resource-group production --name cluster --node-count 3",
		"az aks scale --resource-group production --name cluster --node-count 5",
		"az aks upgrade --resource-group production --name cluster --kubernetes-version 1.32.0",
		"az aks delete --resource-group production --name cluster --yes",
		"az aks get-credentials --resource-group production --name cluster",
		"az containerapp create --resource-group production --name api --image nginx",
		"az containerapp update --resource-group production --name api --image nginx:latest",
		"az containerapp revision activate --resource-group production --name api --revision api--v2",
		"az webapp deploy --resource-group production --name api --src-path app.zip",
		"az webapp config appsettings list --resource-group production --name api",
		"az webapp config connection-string list --resource-group production --name api",
		"az functionapp create --resource-group production --name worker --storage-account data --consumption-plan-location eastus --runtime node",
		"az functionapp deployment source config-zip --resource-group production --name worker --src app.zip",
		"az keyvault secret list --vault-name production",
		"az keyvault secret show --vault-name production --name database",
		"az keyvault secret set --vault-name production --name database --value password",
		"az storage account keys list --resource-group production --account-name data",
		"az account get-access-token",
		"az account set --subscription production",
		"az login",
		"az logout",
		"az ad sp credential reset --name deployer",
		"az role assignment create --assignee deployer --role Owner --scope /subscriptions/123",
		"az role assignment delete --assignee deployer --role Owner --scope /subscriptions/123",
		"az sql server create --resource-group production --name database --location eastus --admin-user admin --admin-password password",
		"az sql db create --resource-group production --server database --name api",
		"az monitor diagnostic-settings create --name logs --resource resource-id --workspace workspace-id",
		"az monitor log-analytics query-pack query create --resource-group production --query-pack-name shared --query-id list --body '{}'",
		"az deployment group create --resource-group production --template-file main.bicep",
		"az deployment group delete --resource-group production --name current",
		"az search service delete --resource-group production --name index",
		"az config set extension.use_dynamic_install=yes_without_prompt",
		"az extension add --name custom-extension",
		"az rest --method get --url https://management.azure.com/subscriptions",
		"az rest --method patch --url https://management.azure.com/resource --body '{}'",
		"az madeup inspect-resource",
	],
};

const GCLOUD_CORPUS: ProviderCorpus = {
	executable: "gcloud",
	reads: [
		"gcloud compute instances list",
		"gcloud compute instances describe web --zone us-central1-a",
		"gcloud compute instances get-serial-port-output web --zone us-central1-a",
		"gcloud compute images list",
		"gcloud compute machine-types list --zones us-central1-a",
		"gcloud compute zones list",
		"gcloud compute regions list",
		"gcloud compute networks list",
		"gcloud compute networks describe main",
		"gcloud compute networks subnets list --regions us-central1",
		"gcloud compute firewall-rules list",
		"gcloud compute addresses list",
		"gcloud compute disks list",
		"gcloud compute snapshots list",
		"gcloud compute operations list",
		"gcloud compute operations describe operation-id --zone us-central1-a",
		"gcloud storage ls gs://example-bucket",
		"gcloud storage buckets list",
		"gcloud storage buckets describe gs://example-bucket",
		"gcloud storage objects list gs://example-bucket",
		"gcloud storage objects describe gs://example-bucket/public.json",
		"gcloud storage cat gs://example-bucket/public.json",
		"gcloud storage du 'gs://example-bucket/**'",
		"gcloud storage hash gs://example-bucket/public.json",
		"gcloud projects list",
		"gcloud projects describe project-id",
		"gcloud projects get-iam-policy project-id",
		"gcloud policy-troubleshoot iam //cloudresourcemanager.googleapis.com/projects/project-id --principal-email reader@example.com --permission resourcemanager.projects.get",
		"gcloud organizations list",
		"gcloud organizations describe 123",
		"gcloud resource-manager folders list --organization 123",
		"gcloud resource-manager folders describe 456",
		"gcloud iam service-accounts list",
		"gcloud iam service-accounts describe reader@project.iam.gserviceaccount.com",
		"gcloud iam service-accounts get-iam-policy reader@project.iam.gserviceaccount.com",
		"gcloud iam service-accounts keys list --iam-account reader@project.iam.gserviceaccount.com",
		"gcloud container clusters list",
		"gcloud container clusters describe production --region us-central1",
		"gcloud container node-pools list --cluster production --region us-central1",
		"gcloud container node-pools describe system --cluster production --region us-central1",
		"gcloud container operations list --region us-central1",
		"gcloud run services list --region us-central1",
		"gcloud run services describe api --region us-central1",
		"gcloud run revisions list --service api --region us-central1",
		"gcloud run jobs list --region us-central1",
		"gcloud run jobs describe worker --region us-central1",
		"gcloud run jobs executions list --job worker --region us-central1",
		"gcloud functions list --regions us-central1",
		"gcloud functions describe worker --gen2 --region us-central1",
		"gcloud functions logs read worker --gen2 --region us-central1",
		"gcloud sql instances list",
		"gcloud sql instances describe database",
		"gcloud sql databases list --instance database",
		"gcloud sql users list --instance database",
		"gcloud sql operations list --instance database",
		"gcloud logging read 'severity>=ERROR' --limit 20",
		"gcloud logging logs list",
		"gcloud logging sinks list",
		"gcloud logging sinks describe archive",
		"gcloud builds list",
		"gcloud builds describe build-id",
		"gcloud builds log build-id",
		"gcloud artifacts repositories list --location us-central1",
		"gcloud artifacts repositories describe images --location us-central1",
		"gcloud artifacts docker images list us-central1-docker.pkg.dev/project/images",
		"gcloud artifacts versions list --package api --repository images --location us-central1",
		"gcloud pubsub topics list",
		"gcloud pubsub topics describe events",
		"gcloud pubsub subscriptions list",
		"gcloud pubsub subscriptions describe worker",
		"gcloud kms keyrings list --location global",
		"gcloud kms keyrings describe application --location global",
		"gcloud kms keys list --keyring application --location global",
		"gcloud kms keys versions get-public-key 1 --key key --keyring application --location global",
		"gcloud app describe",
		"gcloud app versions list",
		"gcloud app logs tail",
		"gcloud deploy delivery-pipelines list --region us-central1",
		"gcloud deploy delivery-pipelines describe api --region us-central1",
		"gcloud deploy releases list --delivery-pipeline api --region us-central1",
		"gcloud scheduler jobs list --location us-central1",
		"gcloud scheduler jobs describe cleanup --location us-central1",
		"gcloud services list --enabled",
		"gcloud config list",
		"gcloud config get-value project",
		"gcloud config configurations list",
		"gcloud config configurations describe default",
		"gcloud auth list",
		"gcloud components list",
		"gcloud info",
	],
	approvals: [
		"gcloud compute instances create web --zone us-central1-a",
		"gcloud compute instances start web --zone us-central1-a",
		"gcloud compute instances stop web --zone us-central1-a",
		"gcloud compute instances delete web --zone us-central1-a",
		"gcloud compute instances suspend list --zone us-central1-a",
		"gcloud compute instances resume show --zone us-central1-a",
		"gcloud compute instances reset get --zone us-central1-a",
		"gcloud compute disks snapshot list --snapshot-names snapshot-1 --zone us-central1-a",
		"gcloud compute images deprecate get --state DEPRECATED",
		"gcloud compute instances simulate-maintenance-event list --zone us-central1-a",
		"gcloud compute networks create main --subnet-mode custom",
		"gcloud compute firewall-rules create allow-ssh --network main --allow tcp:22",
		"gcloud compute instance-groups managed abandon-instances list --instances web --zone us-central1-a",
		"gcloud compute instance-groups managed recreate-instances show --instances web --zone us-central1-a",
		"gcloud compute ssh list --zone us-central1-a",
		"gcloud storage buckets create gs://new-bucket",
		"gcloud storage buckets update gs://example-bucket --uniform-bucket-level-access",
		"gcloud storage cp ./artifact.zip gs://example-bucket/list",
		"gcloud storage mv gs://example-bucket/old gs://example-bucket/new",
		"gcloud storage rm gs://example-bucket/old",
		"gcloud storage rsync list gs://example-bucket",
		"gcloud storage buckets add-iam-policy-binding gs://example-bucket --member user:admin@example.com --role roles/storage.admin",
		"gcloud projects add-iam-policy-binding project-id --member user:admin@example.com --role roles/owner",
		"gcloud projects remove-iam-policy-binding project-id --member user:admin@example.com --role roles/owner",
		"gcloud resource-manager folders move 456 --destination-organization 123",
		"gcloud resource-manager folders undelete list",
		"gcloud iam service-accounts create deployer",
		"gcloud iam service-accounts keys create key.json --iam-account deployer@project.iam.gserviceaccount.com",
		"gcloud iam service-accounts sign-blob input.txt list --iam-account deployer@project.iam.gserviceaccount.com",
		"gcloud iam service-accounts sign-jwt claims.json show --iam-account deployer@project.iam.gserviceaccount.com",
		"gcloud container clusters create production --region us-central1",
		"gcloud container clusters resize production --num-nodes 5 --region us-central1",
		"gcloud container clusters upgrade production --master --region us-central1",
		"gcloud container clusters delete production --region us-central1",
		"gcloud container clusters get-credentials production --region us-central1",
		"gcloud container node-pools rollback list --cluster production --region us-central1",
		"gcloud run services deploy api --image us-docker.pkg.dev/project/images/api --region us-central1",
		"gcloud run services update api --set-env-vars MODE=prod --region us-central1",
		"gcloud run services replace service.yaml --region us-central1",
		"gcloud run services delete api --region us-central1",
		"gcloud functions deploy worker --gen2 --runtime nodejs22 --region us-central1 --source .",
		"gcloud functions call list --gen2 --region us-central1 --data '{}'",
		"gcloud functions delete worker --gen2 --region us-central1",
		"gcloud sql instances create database --database-version POSTGRES_16 --region us-central1",
		"gcloud sql instances patch database --tier db-custom-2-7680",
		"gcloud sql instances promote-replica list",
		"gcloud sql instances failover show",
		"gcloud sql instances delete database",
		"gcloud pubsub topics publish events --message hello",
		"gcloud pubsub subscriptions pull list --auto-ack --limit 1",
		"gcloud pubsub subscriptions ack list --ack-ids ACK_ID",
		"gcloud pubsub subscriptions seek list --time 2025-01-01T00:00:00Z",
		"gcloud dataproc jobs kill list --region us-central1",
		"gcloud dataflow jobs drain list --region us-central1",
		"gcloud kms decrypt --ciphertext-file encrypted.bin --plaintext-file plaintext.txt --key key --keyring application --location global",
		"gcloud kms encrypt --plaintext-file plaintext.txt --ciphertext-file encrypted.bin --key key --keyring application --location global",
		"gcloud logging sinks create archive storage.googleapis.com/example-bucket",
		"gcloud logging logs delete list",
		"gcloud artifacts repositories create images --repository-format docker --location us-central1",
		"gcloud app deploy app.yaml",
		"gcloud app services set-traffic default --splits version=1",
		"gcloud deploy releases create release-1 --delivery-pipeline api --region us-central1 --source .",
		"gcloud scheduler jobs pause get --location us-central1",
		"gcloud scheduler jobs resume describe --location us-central1",
		"gcloud auth login",
		"gcloud auth application-default login",
		"gcloud auth print-access-token",
		"gcloud auth print-identity-token",
		"gcloud config set project project-id",
		"gcloud config configurations create work",
		"gcloud components install beta",
		"gcloud secrets list",
		"gcloud secrets versions access latest --secret database",
		"gcloud alpha compute instances list",
		"gcloud beta run services list",
		"gcloud --flags-file flags.yaml compute instances list",
		"gcloud madeup inspect-resource",
	],
};

function replaceExecutable(command: string, executable: string): string {
	return command.replace(/^\S+/, executable);
}

function insertAfterExecutable(command: string, option: string): string {
	return command.replace(/^(\S+)/, `$1 ${option}`);
}

function insertAfterFirstGroup(command: string, option: string): string {
	return command.replace(/^(\S+\s+\S+)/, `$1 ${option}`);
}

function variants(corpus: ProviderCorpus, command: string): string[] {
	const globalOption =
		corpus.executable === "aws"
			? "--profile corpus"
			: corpus.executable === "az"
				? "--subscription corpus"
				: "--project corpus";
	const globalOptionWithEquals = globalOption.replace(" ", "=");
	const globalBooleanOption = corpus.executable === "aws" ? "--debug" : corpus.executable === "az" ? "--only-show-errors" : "--quiet";
	const midpoint = Math.floor(corpus.executable.length / 2);
	const obfuscatedExecutable = `${corpus.executable.slice(0, midpoint)}"${corpus.executable.slice(midpoint)}"`;
	return [
		command,
		replaceExecutable(command, `/usr/local/bin/${corpus.executable}`),
		replaceExecutable(command, obfuscatedExecutable),
		`env CORPUS_TEST=1 ${command}`,
		`sudo -n ${command}`,
		insertAfterExecutable(command, globalOption),
		insertAfterExecutable(command, globalOptionWithEquals),
		insertAfterFirstGroup(command, globalOption),
		insertAfterFirstGroup(command, globalBooleanOption),
		`printf ready && ${command}`,
		`${command} | cat`,
	];
}

function assertCorpus(corpus: ProviderCorpus): void {
	assert.ok(corpus.reads.length >= 40, `${corpus.executable} read corpus is too small`);
	assert.ok(corpus.approvals.length >= 40, `${corpus.executable} approval corpus is too small`);
	for (const command of corpus.reads) {
		for (const variant of variants(corpus, command)) {
			assert.equal(evaluateCommand(variant).allow, true, `unexpected approval: ${variant}`);
		}
	}
	for (const command of corpus.approvals) {
		for (const variant of variants(corpus, command)) {
			assert.equal(evaluateCommand(variant).allow, false, `unexpected allow: ${variant}`);
		}
	}
}

function corpusTestName(provider: string, corpus: ProviderCorpus): string {
	const baseCases = corpus.reads.length + corpus.approvals.length;
	const evaluatedCommands = baseCases * variants(corpus, corpus.reads[0]).length;
	return `${provider} cloud policy corpus: ${baseCases} decisions across ${evaluatedCommands} command variants`;
}

test(corpusTestName("AWS", AWS_CORPUS), () => assertCorpus(AWS_CORPUS));
test(corpusTestName("Azure", AZ_CORPUS), () => assertCorpus(AZ_CORPUS));
test(corpusTestName("Google Cloud", GCLOUD_CORPUS), () => assertCorpus(GCLOUD_CORPUS));
